services:
  frontend:
    container_name: gaeb-frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      VUE_APP_API_PATH: http://localhost:5007

  backend:
    container_name: gaeb-backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5007:5007"
